CREATE DATABASE app;
CREATE DATABASE testing;
CREATE USER app_user WITH ENCRYPTED PASSWORD 'pass';
CREATE USER sync_user WITH ENCRYPTED PASSWORD 'pass';

\connect app;
CREATE SCHEMA IF NOT EXISTS application;
GRANT ALL ON SCHEMA application TO app_user;
GRANT ALL ON ALL TABLES IN SCHEMA application TO app_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA application TO app_user;
GRANT ALL ON ALL PROCEDURES IN SCHEMA application TO app_user;
GRANT ALL ON ALL ROUTINES IN SCHEMA application TO app_user;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA application TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON SEQUENCES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON TYPES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON FUNCTIONS TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON ROUTINES TO app_user;

CREATE SCHEMA IF NOT EXISTS entity_cache;
GRANT ALL ON SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL TABLES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL PROCEDURES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL ROUTINES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA entity_cache TO sync_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON TABLES TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON SEQUENCES TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON TYPES TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON FUNCTIONS TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON ROUTINES TO sync_user;


GRANT USAGE ON SCHEMA entity_cache TO app_user;
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA entity_cache TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA entity_cache TO app_user;
ALTER DEFAULT PRIVILEGES FOR USER sync_user IN SCHEMA entity_cache GRANT SELECT, REFERENCES ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES FOR USER sync_user IN SCHEMA entity_cache GRANT SELECT, USAGE ON SEQUENCES TO app_user;

\connect testing;
CREATE SCHEMA IF NOT EXISTS application;
GRANT ALL ON SCHEMA application TO app_user;
GRANT ALL ON ALL TABLES IN SCHEMA application TO app_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA application TO app_user;
GRANT ALL ON ALL PROCEDURES IN SCHEMA application TO app_user;
GRANT ALL ON ALL ROUTINES IN SCHEMA application TO app_user;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA application TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON SEQUENCES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON TYPES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON FUNCTIONS TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA application GRANT ALL ON ROUTINES TO app_user;

CREATE SCHEMA IF NOT EXISTS entity_cache;
GRANT ALL ON SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL TABLES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL PROCEDURES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL ROUTINES IN SCHEMA entity_cache TO sync_user;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA entity_cache TO sync_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON TABLES TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON SEQUENCES TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON TYPES TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON FUNCTIONS TO sync_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity_cache GRANT ALL ON ROUTINES TO sync_user;


GRANT USAGE ON SCHEMA entity_cache TO app_user;
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA entity_cache TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA entity_cache TO app_user;
ALTER DEFAULT PRIVILEGES FOR USER sync_user IN SCHEMA entity_cache GRANT SELECT, REFERENCES ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES FOR USER sync_user IN SCHEMA entity_cache GRANT SELECT, USAGE ON SEQUENCES TO app_user;