<?php

namespace Database\Seeders;

use App\Enums\ClassifierValueType;
use App\Models\CachedEntities\ClassifierValue;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageClassifierValueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ClassifierValue::getModel()
            ->insert(
                collect(static::getData())
                    ->mapSpread(fn (string $name, string $value, string $iso3Code) => [
                        'id' => DB::raw('gen_random_uuid()'),
                        'name' => $name,
                        'value' => $value,
                        'meta' => json_encode(['iso3_code' => $iso3Code]),
                        'type' => ClassifierValueType::Language->value,
                    ])
                    ->all()
            );
    }

    private static function getData(): array
    {
        return [
            ['afrikaani [af-ZA]', 'af-ZA', 'afr'],
            ['albaania [sq-AL]', 'sq-AL', 'sqi'],
            ['amhari [ar-ET]', 'am-ET', 'amh'],
            ['araabia [ar-EG]', 'ar-EG', 'ara'],
            ['araabia [ar-SA]', 'ar-SA', 'ara'],
            ['araabia [ar-MA]', 'ar-MA', 'ara'],
            ['aragoni [an-ES]', 'an-ES', 'arg'],
            ['armeenia [hy-AM]', 'hy-AM', 'hye'],
            ['aserbaidžaani [az-AZ]', 'az-AZ', 'aze'],
            ['assami [as-IN]', 'as-IN', 'asm'],
            ['astuuria [ast-ES]', 'ast-ES', 'ast'],
            ['bajani [bjs-BB]', 'bjs-BB', 'bjs'],
            ['baski [eu-ES]', 'eu-ES', 'eus'],
            ['baškiiri [ba-RU]', 'ba-RU', 'bak'],
            ['belau [pau-PW]', 'pau-PW', 'pau'],
            ['bemba [bem-ZM]', 'bem-ZM', 'bem'],
            ['bengali [bn-IN]', 'bn-IN', 'ben'],
            ['bihari [bh-IN]', 'bh-IN', 'bih'],
            ['birma [my-MM]', 'my-MM', 'mya'],
            ['bislama [bi-VU]', 'bi-VU', 'bis'],
            ['bosnia [bs-BA]', 'bs-BA', 'bos'],
            ['bosnia [bs-Cyrl-BA]', 'bs-Cyrl-BA', 'bos'],
            ['bretooni [br-FR]', 'br-FR', 'bre'],
            ['bulgaaria [bg-BG]', 'bg-BG', 'bul'],
            ['dzongkha [dz-BT]', 'dz-BT', 'dzo'],
            ['eesti [et-EE]', 'et-EE', 'est'],
            ['esperanto [eo-EU]', 'eo-EU', 'epo'],
            ['fääri [fo-FO]', 'fo-FO', 'fao'],
            ['fanagalo [fn-FNG]', 'fn-FNG', 'fng'],
            ['fidži [fj-FJ]', 'fj-FJ', 'fij'],
            ['fulani [ff-FUL]', 'ff-FUL', 'ful'],
            ['gaeli [gd-GB]', 'gd-GB', 'gla'],
            ['galeegi [gl-ES]', 'gl-ES', 'glg'],
            ['ganda [lg-UG]', 'lg-UG', 'lug'],
            ['garo [grt-IN]', 'grt-IN', 'grt'],
            ['grööni [kl-GL]', 'kl-GL', 'kal'],
            ['gruusia [ka-GE]', 'ka-GE', 'kat'],
            ['gudžarati [gu-IN]', 'gu-IN', 'guj'],
            ['gusii [guz-KE]', 'guz-KE', 'guz'],
            ['haiti [ht-HT]', 'ht-HT', 'hat'],
            ['hausa [ha-NE]', 'ha-NE', 'hau'],
            ['havai [haw-US]', 'haw-US', 'haw'],
            ['heebrea [he-IL]', 'he-IL', 'heb'],
            ['hiina [zh-CN]', 'zh-CN', 'zho'],
            ['hiina [zh-HK]', 'zh-HK', 'zho'],
            ['hiina [zh-MO]', 'zh-MO', 'zho'],
            ['hiina [zh-TW]', 'zh-TW', 'zho'],
            ['hiligainoni [hil-PH]', 'hil-PH', 'hil'],
            ['hindi [hi-IN]', 'hi-IN', 'hin'],
            ['hispaania [es-419]', 'es-419', 'spa'],
            ['hispaania [es-AR]', 'es-AR', 'spa'],
            ['hispaania [es-CO]', 'es-CO', 'spa'],
            ['hispaania [es-ES]', 'es-ES', 'spa'],
            ['hispaania [es-MX]', 'es-MX', 'spa'],
            ['hispaania [es-US]', 'es-US', 'spa'],
            ['hollandi [nl-BE]', 'nl-BE', 'nld'],
            ['hollandi [nl-NL]', 'nl-NL', 'nld'],
            ['horvaadi [hr-HR]', 'hr-HR', 'hrv'],
            ['ibo [ibo-NG]', 'ibo-NG', 'ibo'],
            ['iiri [ga-IE]', 'ga-IE', 'gle'],
            ['iloko [ilo-PH]', 'ilo-PH', 'ilo'],
            ['indoneesia [id-ID]', 'id-ID', 'ind'],
            ['inglise [en-AU]', 'en-AU', 'eng'],
            ['inglise [en-CA]', 'en-CA', 'eng'],
            ['inglise [en-GB]', 'en-GB', 'eng'],
            ['inglise [en-IE]', 'en-IE', 'eng'],
            ['inglise [en-IN]', 'en-IN', 'eng'],
            ['inglise [en-NZ]', 'en-NZ', 'eng'],
            ['inglise [en-SG]', 'en-SG', 'eng'],
            ['inglise [en-US]', 'en-US', 'eng'],
            ['inglise [en-ZA]', 'en-ZA', 'eng'],
            ['islandi [is-IS]', 'is-IS', 'isl'],
            ['itaalia [it-CH]', 'it-CH', 'ita'],
            ['itaalia [it-IT]', 'it-IT', 'ita'],
            ['jaapani [ja-JP]', 'ja-JP', 'jpn'],
            ['jaava [jv-ID]', 'jv-ID', 'jav'],
            ['jidiši [yi-YD]', 'yi-YD', 'yid'],
            ['joruba [yo-NG]', 'yo-NG', 'yor'],
            ['kabiili [kab-DZ]', 'kab-DZ', 'kab'],
            ['kabuverdianu [kea-CV]', 'kea-CV', 'kea'],
            ['kalenjin [kln-KE]', 'kln-KE', 'kln'],
            ['kamba [kam-KE]', 'kam-KE', 'kam'],
            ['kamwe [hig-NG]', 'hig-NG', 'hig'],
            ['kannada [kn-IN]', 'kn-IN', 'kan'],
            ['kannada [kr-KAU]', 'kr-KAU', 'kan'],
            ['kareni [kar-MM]', 'kar-MM', 'kar'],
            ['kasahhi [kk-KZ]', 'kk-KZ', 'kaz'],
            ['kašmiiri [ks-IN]', 'ks-IN', 'kas'],
            ['katalaani [ca-ES]', 'ca-ES', 'cat'],
            ['keskmargi [mrt-NG]', 'mrt-NG', 'mrt'],
            ['ketšua [qu-PE]', 'qu-PE', 'que'],
            ['khasi [kha-IN]', 'kha-IN', 'kha'],
            ['khmeeri [km-KH]', 'km-KH', 'khm'],
            ["k'iche [quc-GT]", 'quc-GT', 'quc'],
            ['kigirjama [nyf-KE]', 'nyf-KE', 'nyf'],
            ['kikuju [kik-KE]', 'kik-KE', 'kik'],
            ['kirgiisi [ky-KG]', 'ky-KG', 'kir'],
            ['kiribati [gil-KI]', 'gil-KI', 'gil'],
            ['komoori [zdj-KM]', 'zdj-KM', 'zdj'],
            ['kõmri [cy-GB]', 'cy-GB', 'cym'],
            ['konkani [kok-IN]', 'kok-IN', 'kok'],
            ['koosa [xh-ZA]', 'xh-ZA', 'xho'],
            ['kopti [cop-EG]', 'cop-EG', 'cop'],
            ['korea [ko-KR]', 'ko-KR', 'kor'],
            ['kreeka [el-GR]', 'el-GR', 'ell'],
            ['kurdi [ckb-IQ]', 'ckb-IQ', 'kur'],
            ['kurdi [ku-KMR]', 'ku-KMR', 'kur'],
            ['ladina [la-XN]', 'la-XN', 'lat'],
            ['lao [lo-LA]', 'lo-LA', 'lao'],
            ['läti [lv-LV]', 'lv-LV', 'lav'],
            ['leedu [lt-LT]', 'lt-LT', 'lit'],
            ['letseburgi [lb-LU]', 'lb-LU', 'ltz'],
            ['lingala [ln-LIN]', 'ln-LIN', 'lin'],
            ['lõunandebele [nr-ZA]', 'nr-ZA', 'nbl'],
            ['luba-kasai [lua-CD]', 'lua-CD', 'lua'],
            ['luo [luo-KE]', 'luo-KE', 'luo'],
            ['lušei [lus-IN]', 'lus-IN', 'lus'],
            ['maasai [mas-KE]', 'mas-KE', 'mas'],
            ['mäemari [mrj-RU]', 'mrj-RU', 'mrj'],
            ['makedoonia [mk-MK]', 'mk-MK', 'mkd'],
            ['malagassi [mg-MG]', 'mg-MG', 'mlg'],
            ['malai [ms-MY]', 'ms-MY', 'msa'],
            ['malajalami [ml-IN]', 'ml-IN', 'mal'],
            ['maldiivi [dv-MV]', 'dv-MV', 'div'],
            ['malta [mt-MT]', 'mt-MT', 'mlt'],
            ['manipuri [mni-IN]', 'mni-IN', 'mni'],
            ['mänksi [gv-IM]', 'gv-IM', 'glv'],
            ['maoori [mi-NZ]', 'mi-NZ', 'mri'],
            ['marathi [mr-IN]', 'mr-IN', 'mar'],
            ['maršalli [mh-MH]', 'mh-MH', 'mah'],
            ['mende [men-SL]', 'men-SL', 'men'],
            ['meru [mer-KE]', 'mer-KE', 'mer'],
            ['mongoli [mn-MN]', 'mn-MN', 'mon'],
            ['montenegro [sr-ME]', 'sr-ME', 'cnr'],
            ['ndau [ndc-MZ]', 'ndc-MZ', 'ndc'],
            ['nepali [ne-NP]', 'ne-NP', 'nep'],
            ['niidumari [mhr-RU]', 'mhr-RU', 'mhr'],
            ['niue [niu-NU]', 'niu-NU', 'niu'],
            ['njandža  [ny-MW]', 'ny-MW', 'nya'],
            ['norra [nn-NO]', 'nn-NO', 'nno'],
            ['norra [nb-NO]', 'nb-NO', 'nob'],
            ['odia [ory-IN]', 'ory-IN', 'ory'],
            ['oksitaani  [oc-ES]', 'oc-ES', 'oci'],
            ['oksitaani  [oc-FR]', 'oc-FR', 'oci'],
            ['paali [pi-IN]', 'pi-IN', 'pli'],
            ['pandžabi [pa-IN]', 'pa-IN', 'pan'],
            ['pandžabi [pnb-PK]', 'pnb-PK', 'pan'],
            ['papiamento [pap-CW]', 'pap-CW', 'pap'],
            ['pärsia [fa-AF]', 'fa-AF', 'fas'],
            ['pärsia [fa-IR]', 'fa-IR', 'fas'],
            ['pedi [nso-ZA]', 'nso-ZA', 'nso'],
            ['pijin [pis-SB]', 'pis-SB', 'pis'],
            ['pilipino [fil-PH]', 'fil-PH', 'fil'],
            ['poola [pl-PL]', 'pl-PL', 'pol'],
            ['portugali [pt-BR]', 'pt-BR', 'por'],
            ['portugali [pt-PT]', 'pt-PT', 'por'],
            ['potavatomi [pot-US]', 'pot-US', 'pot'],
            ['prantsuse [fr-BE]', 'fr-BE', 'fra'],
            ['prantsuse [fr-CA]', 'fr-CA', 'fra'],
            ['prantsuse [fr-CH]', 'fr-CH', 'fra'],
            ['prantsuse [fr-FR]', 'fr-FR', 'fra'],
            ['puštu [ps-PK]', 'ps-PK', 'pus'],
            ['rohingja [rhg-MM]', 'rhg-MM', 'rhg'],
            ['romanši [rm-RO]', 'rm-RO', 'roh'],
            ['romanši [roh-CH]', 'roh-CH', 'roh'],
            ['rootsi [sv-SE]', 'sv-SE', 'swe'],
            ['ruanda [rw-RW]', 'rw-RW', 'kin'],
            ['rumeenia [ro-RO]', 'ro-RO', 'ron'],
            ['rundi [rn-BI]', 'rn-BI', 'run'],
            ['rundi [run-BI]', 'run-BI', 'run'],
            ['saksa [de-AT]', 'de-AT', 'deu'],
            ['saksa [de-CH]', 'de-CH', 'deu'],
            ['saksa [de-DE]', 'de-DE', 'deu'],
            ['samoa [sm-WS]', 'sm-WS', 'smo'],
            ['sango [sg-CF]', 'sg-CF', 'sag'],
            ['sanskriti [sa-IN]', 'sa-IN', 'san'],
            ['santali [sat-IN]', 'sat-IN', 'sat'],
            ['sebu [cb-PH]', 'cb-PH', 'ceb'],
            ['seišelli [crs-SC]', 'crs-SC', 'crs'],
            ['sena [seh-ZW]', 'seh-ZW', 'seh'],
            ['serbia [sr-Cyrl-RS]', 'sr-Cyrl-RS', 'srp'],
            ['serbia [sr-Latn-RS]', 'sr-Latn-RS', 'srp'],
            ['sindhi [snd-PK]', 'snd-PK', 'snd'],
            ['singali [si-LK]', 'si-LK', 'sin'],
            ['slovaki [sk-SK]', 'sk-SK', 'slk'],
            ['sloveeni [sl-SI]', 'sl-SI', 'slv'],
            ['somaali [so-SO]', 'so-SO', 'som'],
            ['šona [sn-ZW]', 'sn-ZW', 'sna'],
            ['soome [fi-FI]', 'fi-FI', 'fin'],
            ['sotho [st-LS]', 'st-LS', 'sot'],
            ['sranani [srn-SR]', 'srn-SR', 'srn'],
            ['suahiili [sw-KE]', 'sw-KE', 'swa'],
            ['sunda [su-ID]', 'su-ID', 'sun'],
            ['suulu [zu-ZA]', 'zu-ZA', 'zul'],
            ['taani [da-DK]', 'da-DK', 'dan'],
            ['tadžiki [tg-TJ]', 'tg-TJ', 'tgk'],
            ['tagalogi [tl-PH]', 'tl-PH', 'tgl'],
            ['tahiti [ty-PF]', 'ty-PF', 'tah'],
            ['tai [th-TH]', 'th-TH', 'tha'],
            ['tamili [ta-IN]', 'ta-IN', 'tam'],
            ['tamili [ta-LK]', 'ta-LK', 'tam'],
            ['tatari [tt-RU]', 'tt-RU', 'tat'],
            ['telugu [te-IN]', 'te-IN', 'tel'],
            ['tetumi [tet-TL]', 'tet-TL', 'tet'],
            ['tigrinja [ti-ET]', 'ti-ET', 'tir'],
            ['tiibeti [bo-CN]', 'bo-CN', 'bod'],
            ['tokelau [tkl-TK]', 'tkl-TK', 'tkl'],
            ['tok-pisini [tpi-PG]', 'tpi-PG', 'tpi'],
            ['tonga [to-TO]', 'to-TO', 'ton'],
            ['tšamorro [ch-GU]', 'ch-GU', 'cha'],
            ['tšatgaija [ctg-BD]', 'ctg-BD', 'ctg'],
            ['tšehhi [cs-CZ]', 'cs-CZ', 'ces'],
            ['tšerokii [chr-US]', 'chr-US', 'chr'],
            ['tsonga [ts-ZA]', 'ts-ZA', 'tso'],
            ['tsvana [tn-BW]', 'tn-BW', 'tsn'],
            ['tsvana [tn-ZA]', 'tn-ZA', 'tsn'],
            ['tswa [tsc-MZ]', 'tsc-MZ', 'tsc'],
            ['tuareegi [tmh-DZ]', 'tmh-DZ', 'tmh'],
            ['türgi [tr-TR]', 'tr-TR', 'tur'],
            ['türkmeeni [tk-TM]', 'tk-TM', 'tuk'],
            ['tuvalu [tvl-TV]', 'tvl-TV', 'tvl'],
            ['udmurdi [udm-RU]', 'udm-RU', 'udm'],
            ['uighuri [uig-CN]', 'uig-CN', 'uig'],
            ['ukraina [uk-UA]', 'uk-UA', 'ukr'],
            ['uma [ppk-ID]', 'ppk-ID', 'ppk'],
            ['ungari [hu-HU]', 'hu-HU', 'hun'],
            ['urdu [ur-PK]', 'ur-PK', 'urd'],
            ['usbeki [uz-UZ]', 'uz-UZ', 'uzb'],
            ['valgemiao [hmn-CN]', 'hmn-CN', 'hmn'],
            ['valgevene [be-BY]', 'be-BY', 'bel'],
            ['vanasüüria [syc-TR]', 'syc-TR', 'syc'],
            ['vandala [mfi-CM]', 'mfi-CM', 'mfi'],
            ['vandala [mfi-NG]', 'mfi-NG', 'mfi'],
            ['vene [ru-RU]', 'ru-RU', 'rus'],
            ['vietnami [vi-VN]', 'vi-VN', 'vie'],
            ['volofi [wo-SN]', 'wo-SN', 'wol'],
        ];
    }
}
